<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>Preview</LangVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UserSecretsId>5c1160f9-85a5-40a3-85ac-92f00b27e1b4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Blazor\**" />
    <Compile Remove="Obsolete\**" />
    <Compile Remove="Reactive\**" />
    <EmbeddedResource Remove="Blazor\**" />
    <EmbeddedResource Remove="Obsolete\**" />
    <EmbeddedResource Remove="Reactive\**" />
    <None Remove="Blazor\**" />
    <None Remove="Obsolete\**" />
    <None Remove="Reactive\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Serilog.Sinks.TestCorrelator" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="MartinCostello.Logging.XUnit" />
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Verify.Bunit" />
    <PackageReference Include="bunit.core" />
    <PackageReference Include="bunit.web" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.categories" />
    <PackageReference Include="Verify.Xunit" />
    <PackageReference Include="MELT.Xunit" />
    <PackageReference Include="MELT" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
    <PackageReference Include="SerilogTracing" />
    <PackageReference Include="SerilogTracing.Expressions" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.XUnit" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="Serilog.Extensions.Logging" />

    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataFlow\DataFlow.csproj" />
    <ProjectReference Include="..\Benchmarks\Benchmarks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DataFlow\docs\" />
  </ItemGroup>

  <Import Project="..\Tests.Shared\Tests.Shared.projitems" Label="Shared" />

</Project>