<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <PackageId>Uniun.DataFlow.Blazor</PackageId>
    <Title>Uniun DataFlow Blazor</Title>
    <Authors>Darrell Tunnell</Authors>
    <Company>Uniun Technology Ltd</Company>
    <Product>Uniun</Product>
    <Description>Blazor UI components for real-time visualization and monitoring of DataFlow pipeline executions.</Description>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/uniun-technology/dataflow</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DataFlow.Blazor.Shared/DataFlow.Blazor.Shared.csproj" />
  </ItemGroup>

</Project>
