<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Uniun.DataFlow.OpenTelemetry.Legacy</PackageId>
    <RootNamespace>Uniun.DataFlow.OpenTelemetry</RootNamespace>
    <LangVersion>preview</LangVersion>
    <Title>Uniun DataFlow OpenTelemetry</Title>
    <Authors>Darrell Tunnell</Authors>
    <Company>Uniun Technology Ltd</Company>
    <Product>Uniun</Product>
    <Description>Adds companion OTEL apis for observation of DataFlows.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/uniun-technology/dataflow</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Api" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataFlow\DataFlow.Legacy.csproj" />
  </ItemGroup>

</Project>
