namespace Tests.DataFlow;

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Shouldly;
using Uniun.DataFlow;
using Uniun.DataFlow.Actor;
using Uniun.DataFlow.Blocks;
using Uniun.DataFlow.Builder.Graph;
using Uniun.DataFlow.Metrics;
using Xunit;
using Xunit.Abstractions;

/// <summary>
/// Tests demonstrating branch-based concurrency with BroadcastBlock fanout.
/// Includes real-world examples and DI scoping validation.
/// </summary>
[IntegrationTest]
public class BranchBasedConcurrencyTests
{
    private readonly ITestOutputHelper _output;
    private readonly ServiceCollection _services;

    public BranchBasedConcurrencyTests(ITestOutputHelper output)
    {
        _output = output;
        _services = new ServiceCollection();
        AddDefaultServices(_services);
    }

    private void AddDefaultServices(IServiceCollection services)
    {
        services.AddLogging(builder => builder.AddXUnit(_output));
        services.AddDataFlows();
        services.AddMetrics();
        services.AddDataFlowMetrics();
    }

    private IDataFlowContext CreateContext(string name, Guid guid, IServiceProvider provider, CancellationToken ct = default)
    {
        return DataFlowContextTestUtils.GetContext(name, guid, provider, ct);
    }

    [Fact]
    public async Task Should_ProcessInvoices_WithConcurrentBranches_UsingAutoGeneratedNames()
    {
        // Arrange - Setup an invoice processing pipeline with 5 concurrent processing branches using auto-generated names
        var sp = _services.BuildServiceProvider();
        var builder = new StructuredDataFlowBuilder(sp, "InvoiceProcessing");

        // Simulate 20 invoices to process
        var invoices = Enumerable.Range(1, 20).Select(i => new Invoice
        {
            Id = i,
            Amount = i * 100m,
            CustomerId = $"CUST-{i % 5}" // 5 different customers
        }).ToArray();

        var processedInvoices = new ConcurrentBag<ProcessedInvoice>();

        // 1. Producer: Load invoices
        builder.AddProducer<Invoice>("invoice-loader",
            (IServiceProvider sp) => new InvoiceProducer(invoices));

        // 2. Broadcast for concurrent processing
        builder.AddBroadcast<Invoice>("fanout")
            .ReceiveFrom("invoice-loader");

        // 3. Create 5 concurrent processing branches with auto-generated names
        const int concurrency = 5;
        for (var i = 0; i < concurrency; i++)
        {
            var branchId = i;
            // Branch names are auto-generated: "InvoiceProcessing-fanout-branch-0", "InvoiceProcessing-fanout-branch-1", etc.
            var branch = builder.AddBranch();

            // Each branch: validates, enriches, and saves invoices
            branch.AddTransform<Invoice, ValidatedInvoice>($"validator-{i}",
                sp => new InvoiceValidator(branchId))
                .ReceiveFrom("fanout");

            branch.AddTransform<ValidatedInvoice, EnrichedInvoice>($"enricher-{i}",
                sp => new InvoiceEnricher(branchId))
                .ReceiveFrom($"validator-{i}");

            branch.AddProcessor<EnrichedInvoice>($"saver-{i}",
                sp => new InvoiceSaver(branchId, processedInvoices))
                .ReceiveFrom($"enricher-{i}");
        }

        // Build and execute
        var flow = await builder.Build();

        // Act
        var context = CreateContext("invoice-processing", Guid.NewGuid(), sp);
        await flow.ExecuteAsync(context);

        // Assert
        processedInvoices.Count.ShouldBe(100); // 20 invoices × 5 branches (broadcast semantics!)

        // Verify each branch processed all 20 invoices
        for (var branchId = 0; branchId < concurrency; branchId++)
        {
            var branchInvoices = processedInvoices.Where(p => p.ProcessedByBranch == branchId).ToList();
            branchInvoices.Count.ShouldBe(20);
            branchInvoices.Select(p => p.Id).OrderBy(id => id).ShouldBe(Enumerable.Range(1, 20));
        }
    }

    [Fact]
    public async Task Should_ProcessInvoices_WithConcurrentBranches_InComplexPipeline()
    {
        // Arrange - Setup an invoice processing pipeline with 5 concurrent processing branches
        var sp = _services.BuildServiceProvider();
        var builder = new StructuredDataFlowBuilder(sp, "InvoiceProcessing");

        // Simulate 20 invoices to process
        var invoices = Enumerable.Range(1, 20).Select(i => new Invoice
        {
            Id = i,
            Amount = i * 100m,
            CustomerId = $"CUST-{i % 5}" // 5 different customers
        }).ToArray();

        var processedInvoices = new ConcurrentBag<ProcessedInvoice>();

        // 1. Producer: Load invoices
        builder.AddProducer<Invoice>("invoice-loader",
            (IServiceProvider sp) => new InvoiceProducer(invoices));

        // 2. Broadcast for concurrent processing
        builder.AddBroadcast<Invoice>("fanout")
            .ReceiveFrom("invoice-loader");

        // 3. Create 5 concurrent processing branches
        const int concurrency = 5;
        for (var i = 0; i < concurrency; i++)
        {
            var branchId = i;
            var branch = builder.AddBranch($"processing-branch-{i}");

            // Each branch: validates, enriches, and saves invoices
            branch.AddTransform<Invoice, ValidatedInvoice>($"validator-{i}",
                sp => new InvoiceValidator(branchId))
                .ReceiveFrom("fanout");

            branch.AddTransform<ValidatedInvoice, EnrichedInvoice>($"enricher-{i}",
                sp => new InvoiceEnricher(branchId))
                .ReceiveFrom($"validator-{i}");

            branch.AddProcessor<EnrichedInvoice>($"saver-{i}",
                sp => new InvoiceSaver(branchId, processedInvoices))
                .ReceiveFrom($"enricher-{i}");
        }

        // Build and execute
        var flow = await builder.Build();

        // Act
        var context = CreateContext("invoice-processing", Guid.NewGuid(), sp);
        var startTime = DateTime.UtcNow;
        await flow.ExecuteAsync(context);
        var duration = DateTime.UtcNow - startTime;

        // Assert
        processedInvoices.Count.ShouldBe(100); // 20 invoices * 5 branches = 100 (each branch processes all)
        _output.WriteLine($"Processed {processedInvoices.Count} invoice records in {duration.TotalMilliseconds}ms");

        // Verify all branch IDs were used (confirming concurrency)
        var branchIdsUsed = processedInvoices.Select(i => i.ProcessedByBranch).Distinct().OrderBy(x => x).ToArray();
        branchIdsUsed.ShouldBe(new[] { 0, 1, 2, 3, 4 });

        // Generate and display diagram
        var diagram = builder.Graph.ToMermaidDiagram(
            options: new DiagramRenderOptions
            {
                CollapseConcurrentBranches = true,
                MaxBranchesToShowIndividually = 3
            });

        _output.WriteLine("\nDiagram (collapsed):");
        _output.WriteLine(diagram);
    }

    #region Domain Models

    private class Invoice
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public string CustomerId { get; set; }
    }

    private class ValidatedInvoice
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public string CustomerId { get; set; }
        public bool IsValid { get; set; }
    }

    private class EnrichedInvoice
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public string CustomerId { get; set; }
        public bool IsValid { get; set; }
        public string CustomerName { get; set; }
        public decimal TaxAmount { get; set; }
    }

    private class ProcessedInvoice
    {
        public int Id { get; set; }
        public int ProcessedByBranch { get; set; }
        public DateTime ProcessedAt { get; set; }
    }

    #endregion

    #region Processors

    private class InvoiceProducer : IStreamProducer<Invoice>
    {
        private readonly Invoice[] _invoices;

        public InvoiceProducer(Invoice[] invoices)
        {
            _invoices = invoices;
        }

        public async IAsyncEnumerable<Invoice> ProduceAsync(
            IDataFlowContext context,
            [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken)
        {
            foreach (var invoice in _invoices)
            {
                await Task.Delay(10, cancellationToken); // Simulate loading delay
                yield return invoice;
            }
        }
    }

    private class InvoiceValidator : IStreamTransformer<Invoice, ValidatedInvoice>
    {
        private readonly int _branchId;

        public InvoiceValidator(int branchId)
        {
            _branchId = branchId;
        }

        public async IAsyncEnumerable<ValidatedInvoice> TransformAsync(
            IDataFlowContext context,
            IAsyncEnumerable<Invoice> input,
            [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken)
        {
            await foreach (var invoice in input.WithCancellation(cancellationToken))
            {
                await Task.Delay(20, cancellationToken); // Simulate validation work
                yield return new ValidatedInvoice
                {
                    Id = invoice.Id,
                    Amount = invoice.Amount,
                    CustomerId = invoice.CustomerId,
                    IsValid = invoice.Amount > 0
                };
            }
        }
    }

    private class InvoiceEnricher : IStreamTransformer<ValidatedInvoice, EnrichedInvoice>
    {
        private readonly int _branchId;

        public InvoiceEnricher(int branchId)
        {
            _branchId = branchId;
        }

        public async IAsyncEnumerable<EnrichedInvoice> TransformAsync(
            IDataFlowContext context,
            IAsyncEnumerable<ValidatedInvoice> input,
            [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken)
        {
            await foreach (var invoice in input.WithCancellation(cancellationToken))
            {
                await Task.Delay(15, cancellationToken); // Simulate enrichment work
                yield return new EnrichedInvoice
                {
                    Id = invoice.Id,
                    Amount = invoice.Amount,
                    CustomerId = invoice.CustomerId,
                    IsValid = invoice.IsValid,
                    CustomerName = $"Customer {invoice.CustomerId}",
                    TaxAmount = invoice.Amount * 0.2m
                };
            }
        }
    }

    private class InvoiceSaver : IStreamProcessor<EnrichedInvoice>
    {
        private readonly int _branchId;
        private readonly ConcurrentBag<ProcessedInvoice> _processedInvoices;

        public InvoiceSaver(int branchId, ConcurrentBag<ProcessedInvoice> processedInvoices)
        {
            _branchId = branchId;
            _processedInvoices = processedInvoices;
        }

        public async Task ProcessAsync(
            IDataFlowContext context,
            IAsyncEnumerable<EnrichedInvoice> input,
            CancellationToken cancellationToken)
        {
            await foreach (var invoice in input.WithCancellation(cancellationToken))
            {
                await Task.Delay(10, cancellationToken); // Simulate save operation
                _processedInvoices.Add(new ProcessedInvoice
                {
                    Id = invoice.Id,
                    ProcessedByBranch = _branchId,
                    ProcessedAt = DateTime.UtcNow
                });
            }
        }
    }

    #endregion

    #region DI Scoping Tests

    [Fact]
    public async Task Should_MaintainSeparateDIScopes_ForEachBranch()
    {
        // Arrange - Verify that each branch gets its own DI scope
        var services = new ServiceCollection();
        AddDefaultServices(services);

        // Register a scoped service to track scope instances
        var scopeInstances = new ConcurrentBag<int>();
        services.AddScoped<ScopedTestService>(sp => new ScopedTestService(scopeInstances));

        var sp = services.BuildServiceProvider();
        var builder = new StructuredDataFlowBuilder(sp, "ScopedTest");

        var items = Enumerable.Range(1, 10).ToArray();
        builder.AddProducer<int>("source", (IServiceProvider sp) => new TestProducer<int>(items));

        builder.AddBroadcast<int>("fanout")
            .ReceiveFrom("source");

        // Create 3 concurrent branches
        for (var i = 0; i < 3; i++)
        {
            var branchBuilder = builder.AddBranch($"branch-{i}");
            var processorBuilder = StructuredDataFlowBuilderExtensions.AddProcessor<int>(branchBuilder, $"processor-{i}",
                (IServiceProvider sp) => new ScopedProcessor(sp.GetRequiredService<ScopedTestService>()));
            processorBuilder.ReceiveFrom("fanout");
        }

        var flow = await builder.Build();

        // Act
        var context = CreateContext("test", Guid.NewGuid(), sp);
        await flow.ExecuteAsync(context);

        // Assert - Should have multiple scope instances (one per branch actor)
        scopeInstances.Count.ShouldBe(3);
        _output.WriteLine($"Total scope instances created: {scopeInstances.Count}");
    }

    private class ScopedTestService
    {
        private readonly ConcurrentBag<int> _scopeInstances;

        public ScopedTestService(ConcurrentBag<int> scopeInstances)
        {
            _scopeInstances = scopeInstances;
            InstanceId = scopeInstances.Count + 1;
            _scopeInstances.Add(InstanceId);
        }

        public int InstanceId { get; }
    }

    private class ScopedProcessor : IStreamProcessor<int>
    {
        private readonly ScopedTestService _scopedService;

        public ScopedProcessor(ScopedTestService scopedService)
        {
            _scopedService = scopedService;
        }

        public async Task ProcessAsync(
            IDataFlowContext context,
            IAsyncEnumerable<int> input,
            CancellationToken cancellationToken)
        {
            await foreach (var item in input.WithCancellation(cancellationToken))
            {
                // Just consume the items
                await Task.Yield();
            }
        }
    }

    #endregion
}
